import { testAll, testAllNoError, testAllObject } from "../test_utils"
import * as exstr from "./exstr"

testAll(exstr.parseExStr, [
    [["help"], [{ type: "excmd", value: "help" }]],
    [["fillcmdline open"], ["wot"]],
    [["current_url open"], []],
    [["fillcmdline winopen"], []],
    [["current_url winopen"], []],
    [["fillcmdline tabopen"], []],
    [["followpage next"], []],
    [["followpage prev"], []],
    [["urlincrement -1"], []],
    [["urlincrement 1"], []],
    [["urlincrement -1"], []],
    [["urlincrement 1"], []],
    [["current_url tabopen"], []],
    [["clipboard yank"], []],
    [["clipboard yankshort"], []],
    [["clipboard yankcanon"], []],
    [["clipboard yankmd"], []],
    [["clipboard yanktitle"], []],
    [["home"], []],
    [["home true"], []],
    [["clipboard open"], []],
    [["clipboard tabopen"], []],
    [["scrollline 10"], []],
    [["scrollline 10"], []],
    [["scrollline -10"], []],
    [["scrollline 10"], []],
    [["scrollpx -50"], []],
    [["scrollpx 50"], []],
    [["scrollto 100"], []],
    [["scrollto 0"], []],
    [["scrollpage -0.5"], []],
    [["scrollpage 0.5"], []],
    [["scrollto 100 x"], []],
    [["scrollto 0 x"], []],
    [["buffer #"], []],
    [["back"], []],
    [["forward"], []],
    [["jumpprev"], []],
    [["jumpnext"], []],
    [["tabclose"], []],
    [["composite tabprev; sleep 100; tabclose #"], []],
    [["tabclosealltoleft"], []],
    [["tabclosealltoright"], []],
    [["undo"], []],
    [["reload"], []],
    [["reloadhard"], []],
    [["focusinput -l"], []],
    [["changelistjump -1"], []],
    [["tabnext_gt"], []],
    [["tabprev"], []],
    [["tabfirst"], []],
    [["tabfirst"], []],
    [["tablast"], []],
    [["reader"], []],
    [["urlparent"], []],
    [["urlroot"], []],
    [["viewsource"], []],
    [["fillcmdline_notrail"], []],
    [["fillcmdline open search"], []],
    [["fillcmdline tabopen search"], []],
    [["gobble 1 quickmark"], []],
    [["fillcmdline bufferall"], []],
    [["fillcmdline buffer"], []],
    [["qall"], []],
    [["hint"], []],
    [["hint -b"], []],
    [["hint -i"], []],
    [["hint -I"], []],
    [["hint -k"], []],
    [["hint -y"], []],
    [["hint -p"], []],
    [["hint -P"], []],
    [["hint -r"], []],
    [["hint -s"], []],
    [["hint -S"], []],
    [["hint -a"], []],
    [["hint -A"], []],
    [["hint -;"], []],
    [["hint -#"], []],
    [["hint -W exclaim_quiet mpv"], []],
    [["hint -w"], []],
    [["mode ignore"], []],
    [["mode ignore"], []],
    [["mode ignore"], []],
    [
        [
            "fillcmdline Ignore mode is now toggled by pressing <S-Insert> or <C-A-`>",
        ],
        [],
    ],
    [["current_url bmark"], []],
    [["bmark"], []],
    [["zoom 0.1 true"], []],
    [["zoom -0.1 true"], []],
    [["zoom 1"], []],
    [["repeat"], []],
    //[["open https://www.youtube.com/watch?v=M3iOROuTuMA"], []],
    //[["hint -c [class*="expand"],[class="togg"]"], []],
    //[["tabopen https://github.com/cmcaine/tridactyl/issues?utf8=✓&q=sort:updated-desc+"], []],
    //[["open https://github.com/cmcaine/tridactyl/issues?utf8=✓&q=sort:updated-desc+"], []],
    //[["winopen https://github.com/cmcaine/tridactyl/issues?utf8=✓&q=sort:updated-desc+"], []],
    //[["tabopen https://reddit.com/r/pathofexile"], []],
    //[["open https://reddit.com/r/pathofexile"], []],
    //[["winopen https://reddit.com/r/pathofexile"], []],
    //[["find"], []],
])
